const Card = require('./models/Card');

const cards = [
  // ── CASHBACK ──
  {
    id:'sbi-cashback', name:'SBI Cashback', fullName:'SBI Cashback Credit Card', bank:'State Bank of India',
    category:'cashback', annualFee:999, feeWaiver:'Waived on ₹2L/yr spend',
    minIncome:360000, minIncomeLabel:'₹30,000/month', minCreditScore:750,
    applyLink:'https://www.sbicard.com/en/personal/credit-cards/rewards/cashback-sbi-card.page',
    imageUrl:'https://www.sbicard.com/sbi-card-en/assets/media/images/personal/credit-cards/rewards/cashback-sbi-card/cashback-sbi-card.png',
    tag:'Best for Online Shopping', network:'VISA', metal:false,
    g1:'#1a237e', g2:'#283593', g3:'#1565c0', chip:'#ffd700', accent:'#90caf9', logo:'SBI',
    highlightColor:'#1565c0', lightColor:'#e3f2fd',
    keyBenefits:['5% cashback on ALL online spends (no merchant restriction)','1% cashback on offline spends','Auto-credited within 2 days of statement','1% fuel surcharge waiver up to ₹100/month','Waived fee on ₹2L annual spend'],
    bestFor:['Online shoppers','Universal cashback seekers','Digital-first spenders'],
  },
  {
    id:'axis-cashback', name:'Axis Cashback', fullName:'Axis Bank Cashback Credit Card', bank:'Axis Bank',
    category:'cashback', annualFee:999, feeWaiver:'Waived on ₹2L/yr spend',
    minIncome:300000, minIncomeLabel:'₹25,000/month', minCreditScore:700,
    applyLink:'https://www.axisbank.com/retail/cards/credit-card/axis-bank-cashback-credit-card',
    imageUrl:'https://images.axisbank.com/assets/cmsassets/credit_card_images/axis-cashback-credit-card.png',
    tag:'Highest Cashback Rate', network:'VISA', metal:false,
    g1:'#880e4f', g2:'#ad1457', g3:'#c2185b', chip:'#ffd700', accent:'#f48fb1', logo:'AXIS',
    highlightColor:'#c2185b', lightColor:'#fce4ec',
    keyBenefits:['Up to 7% cashback on online spends','0.75% on travel & offline spends','0.5% on utility bill payments','₹1,000 welcome benefit on activation','No minimum spend for activation'],
    bestFor:['High-frequency online spenders','Utility bill payers'],
  },
  {
    id:'hdfc-millennia', name:'HDFC Millennia', fullName:'HDFC Millennia Credit Card', bank:'HDFC Bank',
    category:'cashback', annualFee:1000, feeWaiver:'Waived on ₹1L/yr spend',
    minIncome:420000, minIncomeLabel:'₹35,000/month', minCreditScore:700,
    applyLink:'https://www.hdfcbank.com/personal/pay/cards/credit-cards/millennia-credit-card',
    imageUrl:'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/edf7f7c8-2d1c-4097-97dd-6eb8ea8e90a7',
    tag:'Best Lifestyle Card', network:'Mastercard', metal:false,
    g1:'#004d40', g2:'#00695c', g3:'#00796b', chip:'#ffd700', accent:'#80cbc4', logo:'HDFC',
    highlightColor:'#00796b', lightColor:'#e0f2f1',
    keyBenefits:['5% cashback on Amazon, Flipkart, Swiggy, Zomato, Uber & more','1% on all other spends','Airport lounge access on quarterly milestone','10% cashback on SmartBuy flights & hotels','₹1,000 gift voucher on ₹1L quarterly spend'],
    bestFor:['Millennials','Brand-loyal shoppers','Lifestyle spenders'],
  },
  {
    id:'hsbc-live', name:'HSBC Live+', fullName:'HSBC Live+ Credit Card', bank:'HSBC Bank',
    category:'cashback', annualFee:999, feeWaiver:'Waived on ₹2L/yr spend',
    minIncome:400000, minIncomeLabel:'₹33,000/month', minCreditScore:720,
    applyLink:'https://www.hsbc.co.in/credit-cards/products/live/',
    imageUrl:'https://www.hsbc.co.in/content/dam/hsbc/in/en-in/images/cards/live-plus-credit-card.png',
    tag:'Best Dining & Grocery', network:'Mastercard', metal:false,
    g1:'#bf360c', g2:'#d84315', g3:'#e64a19', chip:'#ffd700', accent:'#ffab91', logo:'HSBC',
    highlightColor:'#e64a19', lightColor:'#fbe9e7',
    keyBenefits:['Up to 10% cashback on dining, grocery & online','1.5% unlimited cashback on all other spends','Complimentary lounge access','1% fuel surcharge waiver','Worldwide Mastercard acceptance'],
    bestFor:['Dining lovers','Grocery spenders','Everyday cashback seekers'],
  },
  // ── REWARDS ──
  {
    id:'hdfc-regalia-gold', name:'HDFC Regalia Gold', fullName:'HDFC Regalia Gold Credit Card', bank:'HDFC Bank',
    category:'rewards', annualFee:2500, feeWaiver:'Waived on ₹4L/yr spend',
    minIncome:600000, minIncomeLabel:'₹50,000/month', minCreditScore:750,
    applyLink:'https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card',
    imageUrl:'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/4f2c80e7-ad86-4783-b028-c5ef7db7b23f',
    tag:'Best All-Rounder', network:'Visa', metal:false,
    g1:'#f57f17', g2:'#ff8f00', g3:'#ffa000', chip:'#c0c0c0', accent:'#ffe082', logo:'HDFC',
    highlightColor:'#ffa000', lightColor:'#fff8e1',
    keyBenefits:['4 Reward Points per ₹150 spent everywhere','5X points on Nykaa, Myntra, Swiggy & more','Complimentary MMT Black Gold membership','12 domestic + 6 international lounge visits','Flight vouchers up to ₹10,000 on milestone'],
    bestFor:['High spenders','Lifestyle + travel combo seekers'],
  },
  {
    id:'axis-atlas', name:'Axis Atlas', fullName:'Axis Bank Atlas Credit Card', bank:'Axis Bank',
    category:'rewards', annualFee:5000, feeWaiver:'No waiver; good renewal benefits',
    minIncome:900000, minIncomeLabel:'₹75,000/month', minCreditScore:750,
    applyLink:'https://www.axisbank.com/retail/cards/credit-card/axis-bank-atlas-credit-card',
    imageUrl:'https://images.axisbank.com/assets/cmsassets/credit_card_images/axis-atlas-credit-card.png',
    tag:'Best Air Miles Card', network:'VISA', metal:false,
    g1:'#1a237e', g2:'#283593', g3:'#303f9f', chip:'#c0c0c0', accent:'#9fa8da', logo:'AXIS',
    highlightColor:'#303f9f', lightColor:'#e8eaf6',
    keyBenefits:['5 EDGE Miles per ₹100 on Hotels & Airlines (direct)','2 EDGE Miles per ₹100 on all other spends','Transfer to 19 airline & hotel loyalty programs','Unlimited domestic + international lounge access','10,000 bonus miles on spend milestones'],
    bestFor:['Frequent flyers','Miles & points collectors'],
  },
  {
    id:'amazon-pay-icici', name:'Amazon Pay ICICI', fullName:'Amazon Pay ICICI Bank Credit Card', bank:'ICICI Bank',
    category:'rewards', annualFee:0, feeWaiver:'Lifetime FREE — no annual fee ever',
    minIncome:240000, minIncomeLabel:'₹20,000/month', minCreditScore:700,
    applyLink:'https://www.amazon.in/cbcc/marketpage',
    imageUrl:'https://images-eu.ssl-images-amazon.com/images/G/31/img22/PrimeShow/cards/AmazonPayICICI.png',
    tag:'Lifetime Free Card', network:'VISA', metal:false,
    g1:'#1b5e20', g2:'#2e7d32', g3:'#388e3c', chip:'#ffd700', accent:'#a5d6a7', logo:'ICICI',
    highlightColor:'#388e3c', lightColor:'#e8f5e9',
    keyBenefits:['5% rewards on Amazon.in (Prime members)','3% on Amazon (non-Prime)','2% at 100+ Amazon Pay partner merchants','1% on all other spends — never expires','Zero joining fee, zero annual fee'],
    bestFor:['Amazon loyalists','Budget-conscious users'],
  },
  // ── TRAVEL ──
  {
    id:'hsbc-travelone', name:'HSBC TravelOne', fullName:'HSBC TravelOne Credit Card', bank:'HSBC Bank',
    category:'travel', annualFee:4999, feeWaiver:'Waived on ₹4L/yr spend',
    minIncome:600000, minIncomeLabel:'₹50,000/month', minCreditScore:750,
    applyLink:'https://www.hsbc.co.in/credit-cards/products/travelone/',
    imageUrl:'https://www.hsbc.co.in/content/dam/hsbc/in/en-in/images/cards/travelone-credit-card.png',
    tag:'Best International Travel', network:'Mastercard', metal:false,
    g1:'#006064', g2:'#00838f', g3:'#0097a7', chip:'#ffd700', accent:'#80deea', logo:'HSBC',
    highlightColor:'#0097a7', lightColor:'#e0f7fa',
    keyBenefits:['Accelerated reward points on travel spends','Transfer points to 20+ airlines at 1:1 ratio','Unlimited domestic + international lounge access','Low forex markup for international use','Complimentary travel insurance'],
    bestFor:['International travellers','Miles & points collectors'],
  },
  {
    id:'idfc-wow', name:'IDFC First WOW!', fullName:'IDFC First WOW! Credit Card', bank:'IDFC First Bank',
    category:'travel', annualFee:0, feeWaiver:'Lifetime FREE (FD-backed secured card)',
    minIncome:0, minIncomeLabel:'No income proof required', minCreditScore:0,
    applyLink:'https://www.idfcfirstbank.com/credit-card/wow',
    imageUrl:'https://www.idfcfirstbank.com/content/dam/idfcfirstbank/images/credit-card/wow-credit-card.png',
    tag:'Zero Forex, Zero Fee', network:'VISA', metal:false,
    g1:'#4a148c', g2:'#6a1b9a', g3:'#7b1fa2', chip:'#ffd700', accent:'#ce93d8', logo:'IDFC',
    highlightColor:'#7b1fa2', lightColor:'#f3e5f5',
    keyBenefits:['ZERO forex markup fee on international spends','4X reward points on all spends (online & offline)','FD-backed — no credit history or income proof needed','1% fuel surcharge waiver up to ₹200/month','Build credit history from scratch'],
    bestFor:['First-time credit users','Budget international travellers','Students & homemakers'],
  },
  {
    id:'hdfc-millennia-travel', name:'HDFC Millennia', fullName:'HDFC Millennia (Travel Benefits)', bank:'HDFC Bank',
    category:'travel', annualFee:1000, feeWaiver:'Waived on ₹1L/yr spend',
    minIncome:420000, minIncomeLabel:'₹35,000/month', minCreditScore:700,
    applyLink:'https://www.hdfcbank.com/personal/pay/cards/credit-cards/millennia-credit-card',
    imageUrl:'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/edf7f7c8-2d1c-4097-97dd-6eb8ea8e90a7',
    tag:'Value Travel Card', network:'Mastercard', metal:false,
    g1:'#004d40', g2:'#00695c', g3:'#00796b', chip:'#ffd700', accent:'#80cbc4', logo:'HDFC',
    highlightColor:'#00796b', lightColor:'#e0f2f1',
    keyBenefits:['10% cashback on SmartBuy flights & hotels','Domestic lounge access on quarterly milestone','5% cashback on Uber & top travel brands','Worldwide Mastercard acceptance','No-cost EMI on travel purchases'],
    bestFor:['Occasional travellers','Domestic flyers'],
  },
  {
    id:'idfc-diamond-reserve', name:'IDFC Diamond Reserve', fullName:'IDFC First Diamond Reserve Credit Card', bank:'IDFC First Bank',
    category:'travel', annualFee:3000, feeWaiver:'Partially reversed on spend milestone',
    minIncome:600000, minIncomeLabel:'₹50,000/month', minCreditScore:720,
    applyLink:'https://www.idfcfirstbank.com/credit-card/diamond-reserve-credit-card',
    imageUrl:'https://www.idfcfirstbank.com/content/dam/idfcfirstbank/images/credit-card/diamond-reserve-credit-card.png',
    tag:'Best All-Round Travel', network:'Visa Infinite', metal:false,
    g1:'#37474f', g2:'#455a64', g3:'#546e7a', chip:'#c0c0c0', accent:'#b0bec5', logo:'IDFC',
    highlightColor:'#546e7a', lightColor:'#eceff1',
    keyBenefits:['Zero forex markup fee on all international spends','2 complimentary lounge visits/quarter (domestic + intl)','Accelerated rewards on incremental monthly spends','Hotel benefits via Visa Infinite network','₹500 movie discount per month via District by Zomato'],
    bestFor:['Mid-premium travellers','All-rounder lifestyle seekers'],
  },
  // ── PREMIUM ──
  {
    id:'hdfc-infinia', name:'HDFC Infinia', fullName:'HDFC Infinia Metal Credit Card', bank:'HDFC Bank',
    category:'premium', annualFee:12500, feeWaiver:'Waived on ₹10L/yr spend',
    minIncome:1800000, minIncomeLabel:'₹1,50,000/month (invite-only)', minCreditScore:800,
    applyLink:'https://www.hdfcbank.com/personal/pay/cards/credit-cards/infinia-metal-edition',
    imageUrl:'https://www.hdfcbank.com/content/api/contentstream-id/723fb80a-2dde-42a3-9793-7ae1be57c87f/b2d6e0b6-49b9-452e-8b48-efdef3e4b9e2',
    tag:"India's #1 Premium Card", network:'Visa Infinite', metal:true,
    g1:'#212121', g2:'#37474f', g3:'#455a64', chip:'#ffd700', accent:'#ffd700', logo:'HDFC',
    highlightColor:'#37474f', lightColor:'#eceff1',
    keyBenefits:['3.33% value-back on ALL spends incl. insurance & utilities','Unlimited domestic + international lounge access','Club Marriott + ITC hotel membership benefits','Best-in-class 2% forex markup','10 Reward Points per ₹150 across every category'],
    bestFor:['HNIs','Frequent international travellers','High spenders above ₹5L/month'],
  },
  {
    id:'idfc-private', name:'IDFC First Private', fullName:'IDFC First Private Credit Card', bank:'IDFC First Bank',
    category:'premium', annualFee:0, feeWaiver:'Invite-only — relationship-based issuance',
    minIncome:3000000, minIncomeLabel:'Invite only — Ultra-HNW clients', minCreditScore:800,
    applyLink:'https://www.idfcfirstbank.com/credit-card/private-credit-card',
    imageUrl:'https://www.idfcfirstbank.com/content/dam/idfcfirstbank/images/credit-card/private-credit-card.png',
    tag:'Ultra Premium — Invite Only', network:'Mastercard World Elite', metal:true,
    g1:'#1a1a2e', g2:'#16213e', g3:'#0f3460', chip:'#ffd700', accent:'#ffd700', logo:'IDFC',
    highlightColor:'#0f3460', lightColor:'#e8eaf6',
    keyBenefits:['Exclusive metal card for ultra-high-net-worth individuals','Dedicated personal relationship manager','Unlimited lounge access + complimentary golf worldwide','Ultra-premium lifestyle rewards programme','Comprehensive luxury lifestyle privileges'],
    bestFor:['Ultra-HNW individuals','IDFC wealth management clients'],
  },
  {
    id:'icici-emeralde-private', name:'ICICI Emeralde Private', fullName:'ICICI Emeralde Private Metal Credit Card', bank:'ICICI Bank',
    category:'premium', annualFee:12499, feeWaiver:'Waived on ₹10L/yr spend',
    minIncome:1800000, minIncomeLabel:'₹1,50,000/month (invite-only)', minCreditScore:800,
    applyLink:'https://www.icicibank.com/personal-banking/cards/credit-card/emeralde-private-metal',
    imageUrl:'https://www.icicibank.com/content/dam/icicibank/india/assets/images/header/icici-emeralde-private-metal-credit-card.png',
    tag:'Highest Reward Rate in India', network:'Visa Infinite', metal:true,
    g1:'#006064', g2:'#004d40', g3:'#1b5e20', chip:'#ffd700', accent:'#ffd700', logo:'ICICI',
    highlightColor:'#004d40', lightColor:'#e0f7fa',
    keyBenefits:['18% reward rate on flights & vouchers via iShop','36% reward rate on hotel bookings via iShop portal','Taj Epicure Plus membership + complimentary free night stay','Unlimited lounge access, only 2% forex markup','Up to 18,000 bonus reward points per calendar month'],
    bestFor:['Hotel & flight power bookers','ICICI wealth management customers'],
  },
  {
    id:'axis-magnus', name:'Axis Magnus', fullName:'Axis Magnus Credit Card', bank:'Axis Bank',
    category:'premium', annualFee:12500, feeWaiver:'Waived on ₹24L/yr spend',
    minIncome:2880000, minIncomeLabel:'₹2,40,000/month', minCreditScore:800,
    applyLink:'https://www.axisbank.com/retail/cards/credit-card/axis-bank-magnus-credit-card',
    imageUrl:'https://images.axisbank.com/assets/cmsassets/credit_card_images/axis-magnus-credit-card.png',
    tag:'Best for Big Spenders', network:'Mastercard World Elite', metal:true,
    g1:'#212121', g2:'#424242', g3:'#616161', chip:'#c0c0c0', accent:'#e0e0e0', logo:'AXIS',
    highlightColor:'#424242', lightColor:'#f5f5f5',
    keyBenefits:['Exceptional milestone-based rewards above ₹1.5L/month spend','Priority Pass unlimited international lounge access','Welcome voucher worth ₹12,500 on joining','14% return rate unlocked above ₹1.5L/month threshold','Perfect for large-ticket luxury purchases'],
    bestFor:['Ultra-high monthly spenders','Luxury lifestyle seekers'],
  },
  // ── STUDENT ──
  {
    id:'idfc-wow-student', name:'IDFC WOW! Student', fullName:'IDFC First WOW! Credit Card (Students)', bank:'IDFC First Bank',
    category:'student', annualFee:0, feeWaiver:'Lifetime FREE',
    minIncome:0, minIncomeLabel:'No income proof required', minCreditScore:0,
    applyLink:'https://www.idfcfirstbank.com/credit-card/wow',
    imageUrl:'https://www.idfcfirstbank.com/content/dam/idfcfirstbank/images/credit-card/wow-credit-card.png',
    tag:'No Income Proof Needed', network:'VISA', metal:false,
    g1:'#4527a0', g2:'#512da8', g3:'#5e35b1', chip:'#ffd700', accent:'#b39ddb', logo:'IDFC',
    highlightColor:'#5e35b1', lightColor:'#ede7f6',
    keyBenefits:['FD-backed — no income proof or credit history required','ZERO forex markup fee for international use','4X reward points on all spends (online & offline)','Build a positive credit history from scratch','Zero documentation, instant digital card'],
    bestFor:['College students','First-time credit card users','NRI students'],
  },
  {
    id:'amazon-pay-student', name:'Amazon Pay ICICI (Student)', fullName:'Amazon Pay ICICI Credit Card', bank:'ICICI Bank',
    category:'student', annualFee:0, feeWaiver:'Lifetime FREE',
    minIncome:240000, minIncomeLabel:'₹20,000/month', minCreditScore:650,
    applyLink:'https://www.amazon.in/cbcc/marketpage',
    imageUrl:'https://images-eu.ssl-images-amazon.com/images/G/31/img22/PrimeShow/cards/AmazonPayICICI.png',
    tag:'Best Free Student Card', network:'VISA', metal:false,
    g1:'#e65100', g2:'#f57c00', g3:'#fb8c00', chip:'#ffd700', accent:'#ffcc80', logo:'ICICI',
    highlightColor:'#fb8c00', lightColor:'#fff3e0',
    keyBenefits:['Zero annual fee — lifetime free forever','5% rewards on Amazon.in (Prime members)','Reward points never expire — accumulate freely','Great cashback on online shopping & food delivery','Easy instant digital approval process'],
    bestFor:['Students with part-time income','Online shopping enthusiasts'],
  },
];

async function seedData() {
  try {
    const count = await Card.countDocuments();
    if (count === 0) {
      await Card.insertMany(cards);
      console.log('🌱 Database seeded with', cards.length, 'cards');
    } else {
      console.log('📦 Database already has data, skipping seed');
    }
  } catch (err) {
    console.error('Seed error:', err.message);
  }
}

module.exports = seedData();
